apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdatavolume1
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresserver
spec:
  serviceName: "postgresserver"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.7
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
        - containerPort: 5432
          name: postgredb
        volumeMounts:
        - name: postgredbdatadir
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
        - name: postgredbdatadir
          persistentVolumeClaim:
            claimName: dbdatavolume1
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdbservice
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgresdb
  clusterIP: None
  selector:
    app: postgres